shopware:
    filesystem:
        private:
            type: "local"
            config:
                root: "%kernel.project_dir%/files"
        public:
            type: "local"
            config:
                root: "%kernel.project_dir%/public"

    cdn:
        url: ~
        strategy: "id"

    api:
        max_limit: 500
        allowed_limits: [1, 5, 9, 10, 25, 50, 75, 100, 500]
        api_browser:
            auth_required: true

    admin_worker:
        enable_admin_worker: true
        poll_interval: 30
        transports: ["default"]

    auto_update:
        enabled: true

    store:
        frw: false

    sitemap:
        batchsize: 100
        custom_urls:
        excluded_urls:
